name: run-tests

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: PHP 8.2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: none

      - name: Validate composer
        run: composer validate --no-check-publish

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction

      - name: Run tests
        run: composer test --no-interaction

      - name: Run static analysis
        run: composer analyse --no-interaction
